os:
  - linux
  - osx

language: node_js

node_js:
  - 6.3.1

branches:
  only:
    - master

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start && sleep 3; fi

script:
  - npm run build
  - npm test

notifications:
  email:
    on_success: never
    on_failure: change
